### ISSUE TITLE
Stale indicator displayed when playing a move with mouse

### ISSUE THREAD

**Issue by johtso** [had3z/lichessTools#1]
Firstly, thanks for making this userscript! Lichess should really incorporate this functionality..

So I've found that it's being temperamental when it comes to playing custom moves in analysis. It seems to sometimes display the indicator of the previous move.

One thought is that instead of listening for keyboard and mouse events, you could listen for DOM events that represent a piece move, then it doesn't matter how the move was played. https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/MutationObserver

**Comment by had3z** [comment]
this was implemented by default in lichess

https://github.com/ornicar/lila/issues/8002

**Comment by johtso** [comment]
Oh wow, that's awesome!
